shader.ScaledText = function () {}
m["shader.ScaledText"] = shader.ScaledText
shader.ScaledText.__name__ = "shader.ScaledText"
shader.ScaledText.getShader = function () {
    null == shader.ScaledText.shader && (shader.ScaledText.shader = new lemongine.ShaderProgram("shader.ScaledText", shader.ScaledText.getFragmentShader(), shader.ScaledText.getVertexShader()), shader.ScaledText.shader.setBuiltInBuffers("vertexPosition", "modelMatrix", "cameraMatrix", "projectionMatrix", "uvPosition"), shader.ScaledText.shader.setAttrib("texClip", "float", 4), shader.ScaledText.shader.setUniform("texSize", [0, 0], "float2"), shader.ScaledText.shader.setUniform("color", [1, 1, 1, 1], "float4"), shader.ScaledText.shader.setUniform("colorOffset", [0, 0, 0, 0], "float4"), shader.ScaledText.shader.setUniform("aliasBleed", .4, "float"), shader.ScaledText.shader.setUniform("mask", [-1, -1, -1, -1], "float4"));
    return shader.ScaledText.shader;
}
shader.ScaledText.getFragmentShader = function () {
    return "precision mediump float;\r\n\t\t\tvarying vec2 uvPositionF;\r\n\t\t\tvarying vec4 texClipF;\r\n\t\t\tvarying vec3 vertexPositionF;\r\n\t\t\t\r\n\t\t\tuniform sampler2D texture;\r\n\t\t\tuniform vec2 texSize;\r\n\t\t\tuniform vec4 colorOffset;\r\n\t\t\tuniform vec4 color;\r\n\t\t\tuniform float aliasBleed;\r\n\t\t\tuniform vec4 mask;\r\n\t\t\tuniform float scale;\r\n\r\n\t\t\tvoid main () {\r\n\t\t\t\tvec2 uv = uvPositionF * texClipF.zw + texClipF.xy;\r\n\t\t\t\t\r\n\t\t\t\tvec2 uvMod = mod(uv.xy, 1.0)*aliasBleed; // aliasBleed puts more weight on the original scale to reduce blurring\r\n\r\n\t\t\t\tvec4 src =\r\n\t\t\t\t\ttexture2D(texture, uv / texSize.xy)*(1.0-uvMod.x)*(1.0-uvMod.y)\r\n\t\t\t\t\t+texture2D(texture, (uv+vec2(.5, 0.0)) / texSize.xy)*uvMod.x*(1.0-uvMod.y)\r\n\t\t\t\t\t+texture2D(texture, (uv+vec2(0.0, .5)) / texSize.xy)*(1.0-uvMod.x)*uvMod.y\r\n\t\t\t\t\t+texture2D(texture, (uv+vec2(.5, .5)) / texSize.xy)*uvMod.x*uvMod.y;\r\n\t\t\t\t\r\n\t\t\t\tsrc.rgba = sqrt(clamp(src.rgba-.25, 0.0, 1.0));\r\n\t\t\t\t\r\n\t\t\t\tsrc.rgb /= src.a;\r\n\t\t\t\tsrc.rgba *= clamp(color*vec4(1.0, 1.0, 1.0, 1.3), 0.0, 1.0); // 1.3 increases lost clarity from antialising\r\n\t\t\t\tsrc.rgb *= src.a;\r\n\r\n\t\t\t\tif(mask.z != -1.0 &&\r\n\t\t\t\t\t(  vertexPositionF.x < mask.x\r\n\t\t\t\t\t|| vertexPositionF.y < mask.y\r\n\t\t\t\t\t|| vertexPositionF.x >= mask.x+mask.z\r\n\t\t\t\t\t|| vertexPositionF.y >= mask.y+mask.w )) {\r\n\t\t\t\t\tdiscard;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\tgl_FragColor = clamp(colorOffset+src, 0.0, 1.0);\r\n\t\t\t}\r\n\t\t";
}
shader.ScaledText.getVertexShader = function () {
    return "precision highp float;\r\n\t\t\tattribute vec3 vertexPosition;\r\n\t\t\tattribute vec2 uvPosition;\r\n\t\t\tattribute vec4 texClip;\r\n\t\t\t\r\n\t\t\tvarying vec4 texClipF;\r\n\t\t\tvarying vec2 uvPositionF;\r\n\t\t\tvarying vec3 vertexPositionF;\r\n\t\t\t\r\n\t\t\tuniform mat4 projectionMatrix;\r\n\t\t\tuniform mat4 cameraMatrix;\r\n\t\t\tuniform mat4 modelMatrix;\r\n\t\t\t\r\n\t\t\tvoid main () {\r\n\t\t\t\tuvPositionF = uvPosition;\r\n\t\t\t\ttexClipF = texClip;\r\n\t\t\t\tvec3 vertexPosition2 = floor(vertexPosition.xyz + .5);\r\n\t\t\t\tvertexPositionF = vertexPosition2;\r\n\t\t\t\t\r\n\t\t\t\tgl_Position = projectionMatrix * cameraMatrix * modelMatrix * vec4(vertexPosition2, 1.0);\r\n\t\t\t}\r\n\t\t\t";
}